name: documentation

on:
  push:
    branches: [ "main", "develop", "181-set-up-github-documentation-with-sphinx" ]
  pull_request:
    branches: [ "main", "develop", "181-set-up-github-documentation-with-sphinx" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme myst_parser
        python -m pip install --upgrade pip
        pip install flake8 pytest wheel numpy scipy ase
        pip install asap3
        pip install mp_api
        pip install custodian
        pip install setuptools_scm
        pip install elastic
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install additional dependencies
      run: |
        pip install ghp-import
    - name: Sphinx build
      run: | 
        sphinx-build . _build
    - name: Build and deploy documentation
      run: |
        ghp-import -n -p -f _build
